### ISSUE TITLE
How can i use payara server with HttpSessionReplacer?

### ISSUE THREAD

**Issue by abu99** [AmadeusITGroup/HttpSessionReplacer#40]
I am using multitenancy and payara server to deploy my application. 
I added the library using gradle.
How do i use this library in payara server?

**Comment by nbogojevic** [comment]
Haven't tested it with glassfish/payera. Two approaches you could try
Adding agent you can try to add agent to command line/jvm options: it would be something like adding `-javagent:$SESSION_PATH/session-agent.jar` where $SESSION_PATH is path to where you've downloaded agent jar. 
Another options is to add a SessionFilter as first filter in chain - this needs to be done in web.xml of your web app.

**Comment by abu99** [comment]
Thank you for your expert feedback.
I have done that but a quick question.
How do i test that the session has been intercepted by the agent?.

**Comment by RafaelAlthaus** [comment]
I did the same thing described by abucreative99, but I'm getting the following error when I open my login page. Any idea why? 

`arning:   StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.NullPointerException
	at org.jboss.weld.context.beanstore.http.AbstractSessionBeanStore.getLockStore(AbstractSessionBeanStore.java:116)
	at org.jboss.weld.context.beanstore.AttributeBeanStore.lock(AttributeBeanStore.java:251)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:90)
	at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:76)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)`

**Comment by ganeshadak** [comment]
adding javaagent to jvm, it's working for Galssfish
